name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify repository structure
      run: ls -R

    - name: Build Docker image
      run: docker build -t devops-practice-demo ./github-actions
