name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show repo structure
      run: ls -R

    - name: Build Docker image
      run: docker build -t devops-practice-demo ./github-actions

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag devops-practice-demo ${{ secrets.DOCKER_USERNAME }}/devops-practice:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-practice:latest
